package Vista;

import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setResizable(false);
        Color Gris=new Color(202, 202, 202); 
        this.getContentPane().setBackground(Gris);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAlimentos = new javax.swing.JMenuItem();
        itemSalsa = new javax.swing.JMenuItem();
        itemTortilla = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemGenerarTaco = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 51));

        lbTitulo.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(26, 26, 29));
        lbTitulo.setText("TRABAJO FINAL TACOTITO'S ");
        lbTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), null, null));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(26, 26, 29)));
        jMenuBar1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(26, 26, 29));
        jMenu1.setText("Cargar Productos");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N

        itemAlimentos.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        itemAlimentos.setForeground(new java.awt.Color(26, 26, 29));
        itemAlimentos.setText("ABM Alimento");
        itemAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlimentosActionPerformed(evt);
            }
        });
        jMenu1.add(itemAlimentos);

        itemSalsa.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        itemSalsa.setForeground(new java.awt.Color(26, 26, 29));
        itemSalsa.setText("ABM Salsa");
        itemSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalsaActionPerformed(evt);
            }
        });
        jMenu1.add(itemSalsa);

        itemTortilla.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        itemTortilla.setForeground(new java.awt.Color(26, 26, 29));
        itemTortilla.setText("ABM Tortilla");
        itemTortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTortillaActionPerformed(evt);
            }
        });
        jMenu1.add(itemTortilla);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(26, 26, 29));
        jMenu3.setText("Tacos");
        jMenu3.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N

        itemGenerarTaco.setBackground(new java.awt.Color(26, 26, 29));
        itemGenerarTaco.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        itemGenerarTaco.setText("Crear taco");
        itemGenerarTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGenerarTacoActionPerformed(evt);
            }
        });
        jMenu3.add(itemGenerarTaco);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(lbTitulo)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lbTitulo)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlimentosActionPerformed
        FrmAlimento frmalimento = new FrmAlimento();
        frmalimento.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemAlimentosActionPerformed

    private void itemSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalsaActionPerformed
        FrmSalsa frmsalsa = new FrmSalsa();
        frmsalsa.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemSalsaActionPerformed

    private void itemTortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTortillaActionPerformed
        FrmTortilla frmtortilla = new FrmTortilla();
        frmtortilla.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemTortillaActionPerformed

    private void itemGenerarTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGenerarTacoActionPerformed
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemGenerarTacoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
        
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAlimentos;
    private javax.swing.JMenuItem itemGenerarTaco;
    private javax.swing.JMenuItem itemSalsa;
    private javax.swing.JMenuItem itemTortilla;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
